### ISSUE TITLE
[Memorable date] Fields accept inputs longer than they should (Moto E, Android 4.4, Chrome 44)

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/usfwds#365]
Right now, the memorable date form's month, day and year fields accept entries longer than 2, 2 and 4 digits respectively:

![memorable date accepts long fields](https://cloud.githubusercontent.com/assets/2092076/9500478/aedf06b8-4bf3-11e5-8388-3d2226849192.png)

**Comment by carodew** [comment]
@mollieru will look at all form fields and see which ones need validation and check with front end on how this might fit into the workflow.

**Comment by jpyuda** [comment]
[The Long Now Foundation](http://longnow.org/) approves of this behavior.

**Comment by carodew** [comment]
I would suggest the following: 

Month input only accepts numbers 1-12, with and without leading 0s. That is the user typing in the number 1 or 01 for January, 2 or 02 for February, and so on, all of these would be valid inputs. The number 34, however, would not be a valid input because it is >12. 

Day input accepts numbers 1-31, with and without leading 0s. 

Year input accepts any four numerical characters.
